//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        public int idAvaliacao { get; set; }
        public string cnpjOficina { get; set; }
        public string cpfCliente { get; set; }
        public double notaServico { get; set; }
        public string descricao { get; set; }
        public int idOrcamento { get; set; }
        public string comentarioFuncionario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Oficina Oficina { get; set; }
    }
}
