//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.ProdutosCompra = new HashSet<ProdutosCompra>();
        }
    
        public int idCompra { get; set; }
        public System.DateTime data { get; set; }
        public string cpfFuncionario { get; set; }
        public int idFornecedor { get; set; }
        public string cnpjOficina { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
        public virtual Oficina Oficina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosCompra> ProdutosCompra { get; set; }
    }
}
