//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotoOficina
    {
        public string cnpjOficina { get; set; }
        public int idFoto { get; set; }
        public string nomeFoto { get; set; }
        public byte[] foto { get; set; }
    
        public virtual Oficina Oficina { get; set; }
    }
}
