//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogOrcamento
    {
        public int idAlteracao { get; set; }
        public int idOrcamento { get; set; }
        public string alteracao { get; set; }
        public string cpfUsuario { get; set; }
        public System.DateTime dataAlteracao { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Orcamento Orcamento { get; set; }
    }
}
