//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensagem
    {
        public System.DateTime data { get; set; }
        public System.TimeSpan hora { get; set; }
        public int idOrcamento { get; set; }
        public string mensagem1 { get; set; }
        public byte status { get; set; }
        public int idMensagem { get; set; }
    
        public virtual Orcamento Orcamento { get; set; }
    }
}
