//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.ProdutosCompra = new HashSet<ProdutosCompra>();
            this.ProdutosServico = new HashSet<ProdutosServico>();
        }
    
        public int idProduto { get; set; }
        public string descricao { get; set; }
        public int quantidade { get; set; }
        public double precoCompra { get; set; }
        public Nullable<double> precoVenda { get; set; }
        public string marca { get; set; }
        public Nullable<System.DateTime> validade { get; set; }
        public string categoria { get; set; }
        public string cnpjOficina { get; set; }
    
        public virtual Oficina Oficina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosCompra> ProdutosCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutosServico> ProdutosServico { get; set; }
    }
}
