//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FixFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicosOrcamento
    {
        public int idOrcamento { get; set; }
        public int idServico { get; set; }
        public string status { get; set; }
    
        public virtual Orcamento Orcamento { get; set; }
        public virtual Servico Servico { get; set; }
    }
}
